# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PPJson' do
pod 'ReactiveCocoa', '~> 4.2.1'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~>3.8.1'
pod 'FLAnimatedImage','~>1.0.12'
use_frameworks!
end

